name = "kpoppulse"
main = ".open-next/worker.js"
compatibility_date = "2026-02-06"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[ai]
binding = "AI"
